In [52]:
from tensorflow.keras.models import load_model
import pickle
import pandas as pd

In [53]:
#load the trained model
model = load_model("model.h5")

#Load the encoder and scaler

with open("label_encoder_gender.pkl", "rb") as f:
    label_encoder_gender = pickle.load(f)

with open("scaler.pkl", "rb") as f:
    scaler = pickle.load(f)

with open("onehot_encoder_geography.pkl", "rb") as f:
    onehot_encoder_geography = pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [54]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [55]:
#one hot encode the Geography feature
geography_encoded = onehot_encoder_geography.transform([[input_data['Geography']]]).toarray()
geography_encoded_df = pd.DataFrame(geography_encoded, columns=onehot_encoder_geography.get_feature_names_out(['Geography']))
geography_encoded_df

c:\Users\OPTLPTP513\anaconda3\envs\tf_env\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [56]:
## Data frame
input_data_df = pd.DataFrame([input_data])

In [57]:
# Encode categoryical variable
input_data_df['Gender'] = label_encoder_gender.transform(input_data_df['Gender'])
input_data_df

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          600    France       1  ...          1               1            50000

[1 rows x 10 columns]

In [58]:
# Concat
input_data_df = pd.concat([input_data_df.drop('Geography', axis=1), geography_encoded_df], axis=1)
input_data_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [59]:
#scaling input data
input_scaled = scaler.transform(input_data_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [60]:
# The Prediction
prediction = model.predict(input_scaled)
print("Churn Probability:", prediction[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step
Churn Probability: 0.061083205