In [1]:
import pandas as pd
import pickle
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [4]:
onehot_encoder_geography = OneHotEncoder(handle_unknown='ignore')
geography_encoded = onehot_encoder_geography.fit_transform(data[['Geography']])
geography_encoded_df = pd.DataFrame(geography_encoded.toarray(), columns=onehot_encoder_geography.get_feature_names_out(['Geography']))
data = pd.concat([data, geography_encoded_df], axis=1)
data.drop(['Geography','RowNumber','CustomerId','Surname'], axis=1, inplace=True)

data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [5]:
#feature and target variable
x = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [6]:
#traing and testing
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
#scaling
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [8]:
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)
with open('onehot_encoder_geography.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geography, file)
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [9]:
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Sequential

In [10]:
#building the model
model = Sequential([
    Input(shape=(x_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)
])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
#compiler model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
import datetime

log_dir = "logs/salary_regression/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)
early_stopping_callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [13]:
history = model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=100,
    callbacks=[tensorboard_callback, early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 100376.0547 - mae: 100376.0547 - val_loss: 98510.4688 - val_mae: 98510.4688
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99582.9844 - mae: 99582.9844 - val_loss: 96890.9922 - val_mae: 96890.9922
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 96751.2109 - mae: 96751.2109 - val_loss: 92733.1562 - val_mae: 92733.1562
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91209.4062 - mae: 91209.4062 - val_loss: 85872.2734 - val_mae: 85872.2734
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 83184.7109 - mae: 83184.7109 - val_loss: 77038.3516 - val_mae: 77038.3516
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 73862.9219 - mae: 73862.9219 - val_loss: 67988.8281 - val_mae: 67988.8281
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 65038.6523 - mae: 65038.6523 - val_loss: 60392.9336 - val_mae: 60392.9336
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 58238.1172 - mae: 58238.1172 - val_loss: 55199.8242 - val_mae: 55199.8242
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 54058.3398 - mae: 54058.3398 - val_loss: 52382.9805 - val_mae: 52382.9805
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51865.7461 - mae: 51865.7461 - val_loss: 51245.4961 - val_mae: 51245.4961
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50962.5703 - mae: 50962.5703 - val_loss: 50903.8242 - val_mae: 50903.8242
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50586.4805 - mae: 50586.4805 - val_loss: 50808.1094 - val_mae: 50808.1094
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50417.3828 - mae: 50417.3828 - val_loss: 50767.3086 - val_mae: 50767.3086
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50315.7617 - mae: 50315.7617 - val_loss: 50734.9688 - val_mae: 50734.9688
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50251.1484 - mae: 50251.1484 - val_loss: 50691.1562 - val_mae: 50691.1562
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50192.6953 - mae: 50192.6953 - val_loss: 50659.3984 - val_mae: 50659.3984
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50136.1211 - mae: 50136.1211 - val_loss: 50638.0078 - val_mae: 50638.0078
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50090.9297 - mae: 50090.9297 - val_loss: 50604.9531 - val_mae: 50604.9531
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50055.3125 - mae: 50055.3125 - val_loss: 50584.8164 - val_mae: 50584.8164
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50017.8477 - mae: 50017.8477 - val_loss: 50554.1602 - val_mae: 50554.1602
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49980.3086 - mae: 49980.3086 - val_loss: 50525.3477 - val_mae: 50525.3477
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49946.0195 - mae: 49946.0195 - val_loss: 50500.4297 - val_mae: 50500.4297
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49920.9062 - mae: 49920.9062 - val_loss: 50481.7266 - val_mae: 50481.7266
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49894.9023 - mae: 49894.9023 - val_loss: 50461.8516 - val_mae: 50461.8516
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49870.5273 - mae: 49870.5273 - val_loss: 50450.8750 - val_mae: 50450.8750
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49849.2930 - mae: 49849.2930 - val_loss: 50443.3789 - val_mae: 50443.3789
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49826.1016 - mae: 49826.1016 - val_loss: 50422.1562 - val_mae: 50422.1562
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49807.8320 - mae: 49807.8320 - val_loss: 50404.3086 - val_mae: 50404.3086
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49790.9062 - mae: 49790.9062 - val_loss: 50402.1406 - val_mae: 50402.1406
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49768.4766 - mae: 49768.4766 - val_loss: 50395.0547 - val_mae: 50395.0547
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49754.7031 - mae: 49754.7031 - val_loss: 50386.8320 - val_mae: 50386.8320
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49733.8008 - mae: 49733.8008 - val_loss: 50390.3203 - val_mae: 50390.3203
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49723.4141 - mae: 49723.4141 - val_loss: 50390.6016 - val_mae: 50390.6016
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49710.2188 - mae: 49710.2188 - val_loss: 50377.5781 - val_mae: 50377.5781
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49695.0469 - mae: 49695.0469 - val_loss: 50367.6523 - val_mae: 50367.6523
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49682.1016 - mae: 49682.1016 - val_loss: 50364.8984 - val_mae: 50364.8984
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49669.9414 - mae: 49669.9414 - val_loss: 50354.2695 - val_mae: 50354.2695
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49656.6758 - mae: 49656.6758 - val_loss: 50352.3828 - val_mae: 50352.3828
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49644.9805 - mae: 49644.9805 - val_loss: 50352.1914 - val_mae: 50352.1914
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49635.7578 - mae: 49635.7578 - val_loss: 50352.8789 - val_mae: 50352.8789
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49624.1992 - mae: 49624.1992 - val_loss: 50339.6055 - val_mae: 50339.6055
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49614.7305 - mae: 49614.7305 - val_loss: 50341.0508 - val_mae: 50341.0508
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49604.3633 - mae: 49604.3633 - val_loss: 50328.4141 - val_mae: 50328.4141
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49595.5781 - mae: 49595.5781 - val_loss: 50335.7031 - val_mae: 50335.7031
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49586.0977 - mae: 49586.0977 - val_loss: 50330.9219 - val_mae: 50330.9219
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49580.4609 - mae: 49580.4609 - val_loss: 50332.5156 - val_mae: 50332.5156
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49569.4570 - mae: 49569.4570 - val_loss: 50318.3633 - val_mae: 50318.3633
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49561.5234 - mae: 49561.5234 - val_loss: 50311.5859 - val_mae: 50311.5859
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49550.9453 - mae: 49550.9453 - val_loss: 50313.3398 - val_mae: 50313.3398
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49546.2266 - mae: 49546.2266 - val_loss: 50318.8711 - val_mae: 50318.8711
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49537.2383 - mae: 49537.2383 - val_loss: 50300.4336 - val_mae: 50300.4336
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49532.3398 - mae: 49532.3398 - val_loss: 50302.6172 - val_mae: 50302.6172
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49527.5938 - mae: 49527.5938 - val_loss: 50303.0938 - val_mae: 50303.0938
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49518.5742 - mae: 49518.5742 - val_loss: 50307.1055 - val_mae: 50307.1055
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49510.7461 - mae: 49510.7461 - val_loss: 50304.1875 - val_mae: 50304.1875
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49503.9453 - mae: 49503.9453 - val_loss: 50296.9414 - val_mae: 50296.9414
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49499.6289 - mae: 49499.6289 - val_loss: 50296.3789 - val_mae: 50296.3789
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49495.8164 - mae: 49495.8164 - val_loss: 50290.6094 - val_mae: 50290.6094
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49487.5508 - mae: 49487.5508 - val_loss: 50290.8125 - val_mae: 50290.8125
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49480.3086 - mae: 49480.3086 - val_loss: 50287.3633 - val_mae: 50287.3633
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49477.2031 - mae: 49477.2031 - val_loss: 50297.5234 - val_mae: 50297.5234
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49474.1172 - mae: 49474.1172 - val_loss: 50306.1328 - val_mae: 50306.1328
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49463.8711 - mae: 49463.8711 - val_loss: 50299.1172 - val_mae: 50299.1172
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49459.3086 - mae: 49459.3086 - val_loss: 50301.1602 - val_mae: 50301.1602
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49458.0078 - mae: 49458.0078 - val_loss: 50299.9727 - val_mae: 50299.9727
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49453.3125 - mae: 49453.3125 - val_loss: 50290.9258 - val_mae: 50290.9258
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49448.7148 - mae: 49448.7148 - val_loss: 50294.6797 - val_mae: 50294.6797
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49441.6562 - mae: 49441.6562 - val_loss: 50302.5703 - val_mae: 50302.5703
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49439.1016 - mae: 49439.1016 - val_loss: 50295.2227 - val_mae: 50295.2227
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49435.4336 - mae: 49435.4336 - val_loss: 50295.2422 - val_mae: 50295.2422

In [14]:
%load_ext tensorboard
%tensorboard --logdir logs/salary_regression/fit

Reusing TensorBoard on port 6006 (pid 17052), started 0:59:18 ago. (Use '!kill 17052' to kill it.)

In [15]:
#Evaluating data
loss, mae = model.evaluate(x_test, y_test)
print(f"Test Loss: {loss}, Test MAE: {mae}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50287.3633 - mae: 50287.3633
Test Loss: 50287.36328125, Test MAE: 50287.36328125

In [16]:
model.save('salary_regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.